name: Build and Publish Docker Image

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version number
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t akshat315/encryption-service:${{ env.VERSION }} .
          docker tag akshat315/encryption-service:${{ env.VERSION }} akshat315/converter-service:latest

      - name: Push Docker image
        run: |
          docker push akshat315/encryption-service:${{ env.VERSION }}
          docker push akshat315/encryption-service:latest
